### ISSUE TITLE
Build failure, FluidParser endOfLine not in scope

### ISSUE THREAD

**Issue by jputcu** [deech/fltkhs#20]
A `cabal install fltkhs` on Fedora 21 results in the following build failure:
~~~~
[3 of 5] Compiling Parser
   ( src/Fluid/Parser.hs, dist/build/fltkhs-fluidtohs/fltkhs-fluidtohs-tmp/Parser.o )
src/Fluid/Parser.hs:96:34: Not in scope: `endOfLine'
src/Fluid/Parser.hs:99:32: Not in scope: `endOfLine'
src/Fluid/Parser.hs:103:45: Not in scope: `crlf'
src/Fluid/Parser.hs:529:28: Not in scope: `endOfLine'
Failed to install fltkhs-0.3.0.0
cabal: Error: some packages failed to install:
fltkhs-0.3.0.0 failed during the building phase. The exception was:
ExitFailure 1
~~~~

The Fltk library has following version, `fltk-config --version`: 1.3.3
`ghc --version` is 7.6.3

**Comment by deech** [comment]
Ah, this is unfortunate. You seem to be using Parsec 3.15 or below. These two functions were introduced in 3.16.

Can you try changing line 124 of fltkhs.cabal from:

```
parsec,
```

to:

```
parsec >= 3.16,
```

and see if that works?

**Comment by jputcu** [comment]
I've changed it to **3.1.6**. And now it is OK

**Comment by deech** [comment]
Ok, thanks I'll close this issue when I upload a new version to Hackage. Really appreciate the bug report.

**Comment by jputcu** [comment]
You're welcome, I'm glad to help out and remove obstacles so more users can enjoy this library.

**Comment by deech** [comment]
Neat! You're the first person who has reported that it compiles and works on GHC 7.6.x. That makes me happy.

**Comment by deech** [comment]
Fixed on Hackage in version 0.3.0.1. Thanks again!
