### ISSUE TITLE
GHC 8.10.3 linking issue

### ISSUE THREAD

**Issue by mtolly** [deech/fltkhs#168]
I wanted to test building with GHC 8.10 to try the new nonmoving GC and ran into a strange error. Currently investigating but figured I would post with results so far.

I cloned `71af56f7` and set `stack.yaml` to `resolver: nightly-2021-01-05`; I'm building on Linux (Manjaro) using the bundled option. When it gets to linking an executable (in this case the included `fltkhs-fluidtohs`, but it also happens with others), I get an error starting with:

```
Linking .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0/build/fltkhs-fluidtohs/fltkhs-fluidtohs ...
/usr/bin/ld: .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0/build/c-lib/libfltkc.a(Fl_EnumerationsC.o): in function `fl_define_FL_ROUND_UP_BOXC':

/stuff/git/fltkhs//stuff/git/fltkhs/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0/build/c-src/Fl_EnumerationsC.cpp:7:0: error:
     undefined reference to `fl_define_FL_ROUND_UP_BOX()'
  |
7 |   FL_EXPORT_C(Fl_Boxtype, fl_define_FL_ROUND_UP_BOXC)(){ return fl_define_FL_ROUND_UP_BOX();}
  | ^
/usr/bin/ld: .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0/build/c-lib/libfltkc.a(Fl_EnumerationsC.o): in function `fl_define_FL_SHADOW_BOXC':

/stuff/git/fltkhs//stuff/git/fltkhs/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0/build/c-src/Fl_EnumerationsC.cpp:8:0: error:
     undefined reference to `fl_define_FL_SHADOW_BOX()'
  |
8 |   FL_EXPORT_C(Fl_Boxtype, fl_define_FL_SHADOW_BOXC)(){ return fl_define_FL_SHADOW_BOX();}
  | ^
/usr/bin/ld: .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0/build/c-lib/libfltkc.a(Fl_EnumerationsC.o): in function `fl_define_FL_ROUNDED_BOXC':

/stuff/git/fltkhs//stuff/git/fltkhs/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0/build/c-src/Fl_EnumerationsC.cpp:9:0: error:
     undefined reference to `fl_define_FL_ROUNDED_BOX()'
  |
9 |   FL_EXPORT_C(Fl_Boxtype, fl_define_FL_ROUNDED_BOXC)(){ return fl_define_FL_ROUNDED_BOX();}
  | ^

(... other similar errors ...)
```

Full log: https://pastebin.com/FbMtAcEB

**Comment by mtolly** [comment]
Not sure what this issue was but the https://github.com/deech/fltkhs/tree/TheGreatConsolidation branch works with 8.10.4 no problem.
